// Generated by https://quicktype.io

export interface Patient {
  id:                             number;
  name:                           string;
  lastname:                       string;
  name_complete:                  string;
  birthday:                       string;
  identifier:                     string;
  document_type:                  string;
  mobile:                         string;
  email:                          string;
  address:                        string;
  other_contact:                  string;
  other_contact_mobile:           string;
  other_contact_pacient_relation: string;
  status:                         boolean;
  gender:                         string;
}

export enum Genders {
  NullGender = "Null Gender",
  Masculino = "Masculino",
  Femenino = "Femenino"
}
