// Generated by https://quicktype.io

export interface Patient {
  id:                               number;
  name:                             string;
  lastname:                         string;
  name_complete:                    string;
  birthday:                         string;
  identifier:                       string;
  document_type:                    string;
  mobile:                           string;
  email:                            string;
  address:                          string;
  other_contact?:                   null;
  other_contact_mobile:             null | string;
  "other contact patient relation": string;
  status:                           boolean | null;
  gender:                           string;
  "other contact"?:                 string;
}
