// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface Patient {
  id:                             number;
  name:                           string;
  lastname:                       string;
  name_complete:                  string;
  birthday:                       string;
  identifier:                     string;
  document_type_id:               string;
  mobile:                         string;
  email:                          string;
  address:                        string;
  other_contact:                  string;
  other_contact_mobile:           string;
  other_contact_pacient_relation: string;
  status:                         boolean;
  gender:                         string;
}

// export interface Patient {
//   id: number;
//   name: string;
//   lastname: string;
//   name_complete: string;
//   birthday: string;
//   identifier: string;
//   document_type_id: string;
//   mobile: string;
//   email: string;
//   address: string;
//   other_contact: string;
//   other_contact_mobile: string;
//   relationship_id: string;
//   status: boolean;
//   gender_id: string;
// }

export enum Genders {
  NullGender = "Null Gender",
  Masculino = "Masculino",
  Femenino = "Femenino"
}
